name: Announcements
version: ${project.version}
main: net.dottsg.announcements.Announcements
api-version: 1.15
authors: [Jamac]
description: Server-wide announcement plugin
website: dottsg.net
commands:
  anaddrandom:
    description: Adds a new announcement to the random pool
    permission: edit
    usage: /announcementaddrandom <name> <message>
    aliases: [announcementaddrandom]
  anaddfixed:
    description: Adds a new announcement that repeats at a given interval
    permission: edit
    usage: /addfixed <name> <tickInterval> <message>
    aliases: [announcementaddfixed]
  anaddonlogin:
    description: Adds a new announcement that displays on login
    permission: edit
    usage: /addonlogin <name> <onFirstLogin> <message>
    aliases: [announcementaddonlogin]
  anremove:
    description: Removes an announcement
    permission: edit
    usage: /remove <name>
    aliases: [announcementremove]
  anchangemessage:
    description: Changes an announcement's message
    permission: edit
    usage: /changemessage <name> <message>
    aliases: [announcementchangemessage]
  anlist:
    description: Lists all announcements
    permission: edit
    usage: /list <page>
    aliases: [announcementlist]
  ansetrandominterval:
    description: Sets the interval of random announcements
    permission: edit
    usage: /setrandominterval <tickInterval>
    aliases: [announcementsetrandominterval]
permissions:
  edit:
    description: enables managing announcements
    default: op
